### ISSUE TITLE
Swish transactions in Adyen 7.0.0 sometimes return "PaymentCompletionDetails contains the following unknown fields: [pp]"

### ISSUE THREAD

**Issue by tieroom** [Adyen/adyen-magento2#1038]
**Describe the bug**
When orders are placed using the payment method Swish, they sometimes receive an error message back from Adyen. This produces an error message in the checkout process for the end customer, leading them to re-try placing the order. But, later a notification comes back from Adyen saying the first transaction was successful. This leaves the customer with duplicate successful orders.

The log produces the following output for the failed transactions:

```
[2021-05-01 13:37:16] AdyenLoggerTest.INFO: JSON Response to Adyen:{"status":400,"errorCode":"702","message":"Structure of PaymentCompletionDetails contains the following unknown fields: [pp]","errorType":"validation"} {"is_exception":false} []
[2021-05-01 13:37:16] AdyenLoggerTest.ERROR: 702: Structure of PaymentCompletionDetails contains the following unknown fields: [pp] {"is_exception":false} []
[2021-05-01 13:37:16] AdyenLoggerTest.ERROR: Unexpected result query parameter. Response: {"error":"Structure of PaymentCompletionDetails contains the following unknown fields: [pp]"} {"is_exception":false} []
[2021-05-01 13:37:16] AdyenLoggerTest.ADYEN_RESULT: Payment for order 5000058650 was unsuccessful, it will be cancelled when the OFFER_CLOSED notification has been processed. {"is_exception":false} []
```

Later the following notification with a different opinion arrives. But at this point it's too late as the customer has placed a new order or abandoned the process altogether.

```
[2021-05-01 13:37:50] AdyenLoggerTest.ADYEN_NOTIFICATION: The content of the notification item is: Array
(
    [amount] => Array
        (
            [currency] => SEK
            [value] => 43800
        )

    [eventCode] => AUTHORISATION
    [eventDate] => 2021-05-01T15:37:29+02:00
    [merchantAccountCode] => ********
    [merchantReference] => 5000058650
    [paymentMethod] => swish
    [pspReference] => 1619198762181265
    [reason] => null
    [success] => true
)
 {"is_exception":false} []
[2021-05-01 13:37:50] AdyenLoggerTest.ADYEN_NOTIFICATION: The result is accepted {"is_exception":false} []
```

**To Reproduce**
This issue occurs intermittently for end customers and we have not figured out what triggers it so we are not able to reproduce.

**Expected behavior**
We expect the Adyen server to directly, during the checkout process, return a message saying the transaction is successful and the end customer to be forwarded to the order success page in magento.

**Magento version**
2.4.2

**Plugin version**
7.0.0

This issue only started occurring after our upgrade to Magento 2.4.2 and Adyen 7.0.0. Previously, on Magento 2.3.6 and Adyen 6.x.x, Swish transactions were being processed fine.

Where are the PaymentCompletionDetails created and what could be adding the field, [pp], which the Adyen server doesn't like?

**Comment by Medialized** [comment]
the same issue happend with "twint".

**Comment by tieroom** [comment]
Turns out we are seeing similar error with PayTrail (Finnish E-banking). Since upgrading to Adyen 7.0.0, all these orders are failing with an error similar to the Swish error:

`[2021-04-28 15:28:26] AdyenLoggerTest.ERROR: Unexpected result query parameter. Response: {"error":"Structure of PaymentCompletionDetails contains the following unknown fields: [type]"} {"is_exception":false} []`

I can see the errors started occurring with Adyen 7.0.0. So it's not Magento 2.4.2 causing the error as we ran with 2.4.2 and Adyen 6.x.x. for a while without these issues.

**Comment by Medialized** [comment]
Twint works now with the latest module update.

**Comment by acampos1916** [comment]
Hello @tieroom @Medialized indeed this was fixed in 7.0.1.

@tieroom could you confirm that you're able to use PayTrail and Swish in that release? I'm closing the issue now but we can reopen it if needed.

Thanks.

**Comment by tieroom** [comment]
@acampos1916 I can confirm Paytrail transactions seem to be coming in fine now. Swish looks better as well but we had a couple of Swish transactions over the weekend with similar (but not exactly the same) issue as before. We were though running a dev version of 7.0.1 so possibly some glitch there. I deployed the full release just now and will let you know if any issues pop up.

**Comment by tieroom** [comment]
@acampos1916 Unfortunately we are still getting errors with Swish after upgrading to the full 7.0.1. Error message is:
`Field 'details' expected to be a Structure but is an Array {"is_exception":false} []`

**Comment by tieroom** [comment]
Here's the full sequence with the error at row 9:

```
[2021-05-17 17:49:24] AdyenLoggerTest.INFO: Request url to Adyen: https://XXX-checkout-live.adyenpayments.com/checkout/v67/paymentMethods {"is_exception":false} []
[2021-05-17 17:49:24] AdyenLoggerTest.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"XXX","countryCode":"SE","shopperLocale":"sv_SE","amount":{"currency":"SEK","value":49800}} {"is_exception":false} []
[2021-05-17 17:49:25] AdyenLoggerTest.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["maestro","amex","diners","discover","mc","visa"],"details":[{"key":"encryptedCardNumber","type":"cardToken"},{"key":"encryptedSecurityCode","type":"cardToken"},{"key":"encryptedExpiryMonth","type":"cardToken"},{"key":"encryptedExpiryYear","type":"cardToken"},{"key":"holderName","optional":true,"type":"text"}],"name":"Kortbetalning","type":"scheme"},{"name":"Swish","type":"swish"},{"name":"Trustly","type":"trustly"}]} {"is_exception":false} []
[2021-05-17 17:50:28] AdyenLoggerTest.INFO: Request url to Adyen: https://XXX-checkout-live.adyenpayments.com/checkout/v67/payments {"is_exception":false} []
[2021-05-17 17:50:28] AdyenLoggerTest.INFO: JSON Request to Adyen:{"merchantAccount":"XXX","shopperReference":"50000588201d141ceb-288a-423f-b6e2-780478079e6d","shopperEmail":"XXX@XXX.com","telephoneNumber":"XXX","shopperName":{hidden},"countryCode":"SE","shopperLocale":"sv_SE","shopperIP":"XXX","billingAddress":{"street":"XXXZ","postalCode":"XXX","city":"XXX","houseNumberOrName":"43","country":"SE"},"deliveryAddress":{"street":"XXX","postalCode":"XXX","city":"XXX","houseNumberOrName":"43","country":"SE"},"amount":{"currency":"SEK","value":49800},"reference":"5000058820","fraudOffset":"0","browserInfo":{"userAgent":"Mozilla\/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/13.1.2 Mobile\/15E148 Safari\/604.1","acceptHeader":"*\/*"},"shopperInteraction":"Ecommerce","recurringProcessingModel":"Subscription","paymentMethod":{"type":"swish"},"riskData":{"clientData":"XXX"},"returnUrl":"https:\/\/www.XXX.se\/adyen\/process\/result\/?merchantReference=5000058820","additionalData":{"allow3DS2":true},"origin":"https:\/\/www.XXX.se","channel":"web","applicationInfo":{"merchantApplication":{"name":"adyen-magento2","version":"7.0.1"},"adyenLibrary":{"name":"adyen-php-api-library","version":"10.1.0"},"adyenPaymentSource":{"version":"7.0.1","name":"adyen-magento2"},"externalPlatform":{"version":"2.4.2","name":"Magento"}}} {"is_exception":false} []
[2021-05-17 17:50:29] AdyenLoggerTest.INFO: JSON Response to Adyen:{"resultCode":"Pending","action":{"paymentData":"Ab02b4***","paymentMethodType":"swish","url":"swish:\/\/paymentrequest?callbackurl=https%3A%2F%2Fwww.XXX.se%2Fadyen%2Fprocess%2Fresult%2F%3FmerchantReference%3D5000058820%26pp%3DSpzKi7pQ%252BZ%252F3XhD6py7W6WSXg23qxmE4w4V6Vw0uAHASghfHlWc6yDXtNH5aXvL%252F3%252FoHlJUMEJa8YCVe%252FFzajsuoGV6NSsXEPPY%252F6tvsa1XOiyBOGaYKg%252BQ5%252BY6G0jPz%252F9CxgidAH2LKpfcHuaRr1A%253D%253D&token=1cvpzCNdRpaWTE9uBxX9e06E1IyRjTHh","qrCodeData":"D1cvpzCNdRpaWTE9uBxX9e06E1IyRjTHh","type":"qrCode"}} {"is_exception":false} []
[2021-05-17 17:50:40] AdyenLoggerTest.INFO: Request url to Adyen: https://XXX-checkout-live.adyenpayments.com/checkout/v67/payments/details {"is_exception":false} []
[2021-05-17 17:50:40] AdyenLoggerTest.INFO: JSON Request to Adyen:{"details":[]} {"is_exception":false} []
[2021-05-17 17:50:40] AdyenLoggerTest.INFO: JSON Response to Adyen:{"status":400,"errorCode":"702","message":"Field 'details' expected to be a Structure but is an Array","errorType":"validation"} {"is_exception":false} []
[2021-05-17 17:50:46] AdyenLoggerTest.INFO: Request url to Adyen: https://XXX-checkout-live.adyenpayments.com/checkout/v67/paymentMethods {"is_exception":false} []
[2021-05-17 17:50:46] AdyenLoggerTest.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"XXX","countryCode":"SE","shopperLocale":"sv_SE","amount":{"currency":"SEK","value":49800},"telephoneNumber":"XXX"} {"is_exception":false} []
[2021-05-17 17:50:46] AdyenLoggerTest.INFO: JSON Response to Adyen:{"paymentMethods":[{"brands":["maestro","amex","diners","discover","mc","visa"],"details":[{"key":"encryptedCardNumber","type":"cardToken"},{"key":"encryptedSecurityCode","type":"cardToken"},{"key":"encryptedExpiryMonth","type":"cardToken"},{"key":"encryptedExpiryYear","type":"cardToken"},{"key":"holderName","optional":true,"type":"text"}],"name":"Kortbetalning","type":"scheme"},{"name":"Swish","type":"swish"},{"name":"Trustly","type":"trustly"}]} {"is_exception":false} []
[2021-05-17 17:51:31] AdyenLoggerTest.INFO: Request url to Adyen: https://XXX-checkout-live.adyenpayments.com/checkout/v67/payments/details {"is_exception":false} []
[2021-05-17 17:51:31] AdyenLoggerTest.INFO: JSON Request to Adyen:{"details":{"payload":"Ab02b4c0!BQABAgAyI5PGqCZmM1c3Q+T1WLuO5o5\/lZEu58TNt0Lnthv7+O5OmV5Z+1ENgHh4rB+0CcJvFIMXFgL3ntxADJqst1k\/QiFkRxox59RwELDQnwmXdlNOWxHbw7IsbY0JdYChmGOkKrQC7WDgSS3EFFqvd5plAxM9783pz2WDvshpNm2tOgoFUZ0VYLgwUjz7lJ8Ne6YRjEkCttrdFsfI2Zy7HeN0AP61yraPUFIoARe2wAuJrgdRV1BViLNMyfhz4+gjSunOkw3VrjiFIdZy1+yUrpoPeZbjfLEP8iBs4xJjen2xTCDKQKlCWyObFylHwG\/0FRUIDbGSeK\/NhDMrWh\/\/iml0A2r1dB6cL4q+bzmjAkwjXvoiWy2hfm7ryGviImJnkVfuEuCcMtmFfBbE5jyLeRn1gR2+QmQN+6ihRrG7VN4+G6Adxj5+bitt9zrrBk4U2mCbWSukrVlLP5q51l6NkS29rMTEuT98pQn9gbUctnCf6YDyzofSiOnq+pWVQmovVhQHERhf+4SlBF9ky0vasbQJXfQ8AgH4CK4577fQNJWJWJ2rJqULKdk4g6RYfAv\/Hpi1gnomTnJHrk32Xaq22ycoGfhM8jHzcUNfCoWICCwJrlrbl4tIDKEpXlQKR8O\/uYgdp+P1DAzBVK7yQl6OrdatUes6+tPnc0HLlT61ju\/nCRBCda0gRyFJs56FW68X+RMaAEp7ImtleSI6IkNDMkQ1Q0FEMEVDNjFDRDE0QUJCRkQyMThBMTFBNTE4QUFFNEMyNTI5MEZFOTlCN0MzMEJBNkMyOTJDNEZFQUYifZKO2xk2AUeC1pO73DM9nvLucKCpSGISdxnGR42yUG8tr28U0kt0FrMUy46FpVUZ2NeH+3YJLwCafOv1mA\/Ug\/EanF3XtI391f7wfehQDTM\/VesDP66JLDHUC1Ip7pZfCz4MH8cprN\/Kj1Gh+kpdhQbWXJCuznLhE1CBjbEBdsLh1qC7md8FutFl98Lw6ojsu6Yt2hXv1ju\/qLyVkYs6"},"paymentData":"Ab02b4***"} {"is_exception":false} []
[2021-05-17 17:51:31] AdyenLoggerTest.INFO: JSON Response to Adyen:{"pspReference":"1519212738284300","resultCode":"Authorised","merchantReference":"5000058820"} {"is_exception":false} []
```

**Comment by acampos1916** [comment]
Hey @tieroom,

I see that the call that fails has an empty `details` object, pretty sure that's the reason for the error. Are you able to debug the payment details function to figure out why is it intermittently empty in your instance? https://github.com/Adyen/adyen-magento2/blob/master/Model/AdyenPaymentDetails.php#L90

**Comment by tieroom** [comment]
@acampos1916 Sorry but I don't have the capability to debug this.

**Comment by tieroom** [comment]
Just noting that this bug remains and the ticket should be re-opened. We still have daily occurrences of Swish transactions that produce the 702 response and result in an error message being displayed to the customer even though the transaction goes through, causing the customer to place multiple orders.

I understand Adyen have identified the root cause internally but it's taking a looooong time to get it fixed.

We are currently on plugin version 7.3.2 on Magento 2.4.3-p1.
