### ISSUE TITLE
Empty response from Adyen lead to frozen shipping step of checkout and error in the console.

### ISSUE THREAD

**Issue by vasiok32k** [Adyen/adyen-magento2#1105]
**Describe the bug**
If response from the Adyen is empty (for example when your Adyen not configured correctly) - it will lead to error in the console of the browser and will be infinite full screen loader on the shipping step.

**Error in the console:**
`Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    initialize path_to_the_theme/Adyen_Payment/js/view/payment/adyen-methods.js:80
    jQuery 4`

**To Reproduce**
1. Make sure that your Adyen plagin in Magento not configured correctly
2. Go to 'Checkout' page
2. You can see that page is frozen via infinite full screen loader on the shipping step of checkout and you can see appropriate error in the console of the browser.

**Expected behavior**
The shipping step of checkout is not frozen via loader and there isn't appropriate error in the console of the browser and you go to the next step.

**Magento version**
**2.4.2-p1**

**Plugin version**
**7.1.0**

**Screenshots**
![image](https://user-images.githubusercontent.com/10946737/125729320-0e97a31e-5c75-40b1-89b9-4f0ffece9823.png)

**Comment by acampos1916** [comment]
Hello @vasiok32k thanks for this report. I believe this is being fixed with this PR https://github.com/Adyen/adyen-magento2/pull/1094 and is going to be released soon. Could you verify if that fix solves this issue for you?

**Comment by vasiok32k** [comment]
Hi @acampos1916 
I tried it and seems like it partly solve the issue (error still showing in the console from catch statement. I solved issue on my project via adding additional statement for the response like 
![image](https://user-images.githubusercontent.com/10946737/125745141-639d29e4-2799-4d2b-b79e-b7b50e60a59c.png)
Please let me know if it also acceptable fix for it. But from other way I agree that try...catch... also good solution for this but I'm not sure that it's needed in this situation because for this informing (for exceptions) exist var/log/adyen/error.log file.

**Comment by acampos1916** [comment]
Thanks @vasiok32k, your fix looks good and should work. Feel free to also contribute any improvements you would like to see in the plugin like this one by opening a PR.

I'll be closing this issue now, cheers!
