### ISSUE TITLE
Adyen 7.3*/8.0 with Magento 2.4.4-beta*

### ISSUE THREAD

**Issue by FredericMartinez** [Adyen/adyen-magento2#1264]
Hello folks!

adyen-magento 7.3.1 or 8.0 is not compatible with Magento 2.4.4-beta* on PHP 8.0

**To Reproduce**

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.4.4-beta2 ee_244-beta2
composer require adyen-magento
php bin/magento setup:di:compile
```

Error:

```
Fatal error: Declaration of Adyen\Payment\Logger\Handler\AdyenBase::isHandling(array $record) must be compatible with Monolog\Handler\AbstractHandler::isHandling(array $record): bool in vendor/adyen/module-payment/Logger/Handler/AdyenBase.php on line 35
```

**Expected behavior**
Adyen should be compiled in `generated` without errors

**Magento version**
2.4.4-beta2

**Plugin version**
8.0
7.3.1

**CLI**
PHP 8.0

**Comment by FredericMartinez** [comment]
I will create a PR, but for the record, 2 methods need to have return casted with `bool` :

* Adyen\Payment\Logger\AdyenLogger => `public function addRecord($level, $message, array $context = []): bool`
* Adyen\Payment\Logger\Handler\AdyenBase  => `public function isHandling(array $record): bool`

**Comment by FredericMartinez** [comment]
After thoses fixes :arrow_up:, it will lead to another [PHP 8.0 issue](https://php.watch/versions/8.0/deprecate-required-param-after-optional):

```
Deprecated Functionality: Required parameter $storeId follows optional parameter $paymentMethodCode in /vendor/adyen/module-payment/Model/Cron.php on line 2206
```

Fix:
```
-protected function _getConfigData($field, $paymentMethodCode = 'adyen_cc', $storeId)
+protected function _getConfigData($field, $paymentMethodCode = 'adyen_cc', $storeId = null)

**Comment by tnaber** [comment]
Thank you for opening this issue and leaving your solutions here! Did you still want to create a PR for this?

**Comment by Morerice** [comment]
Issue was resolved in v8.2.1

**Comment by aligent-lturner** [comment]
@Morerice the issue mentioned in https://github.com/Adyen/adyen-magento2/issues/1264#issuecomment-983961237 has not actually been resolved. While this is just a warning, it is still incorrect code for Magento 2.4.4
