### ISSUE TITLE
When Terms and Condition checkbox is required Google pay and apple not validating it

### ISSUE THREAD

**Issue by sarfarazbheda** [Adyen/adyen-magento2#2547]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**
Activate terms and conditions check box and make it required field. and tru to place order with Google pay and apple pay, it will not validate the term and condition checkbox and order will be placed successfully without selecting it.

**To Reproduce**
1. Go to Admin panel and activate t&c as required field 
2. Click on on Google pay or apple pay button from the checkout page payment section
4.it will show Google payment form directly 

**Expected behavior**
It should validate the t&c checkbox before showing Google pay payment form.

**Magento version**
2.4.6.-p1

**Plugin version**
9.2.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All
 - Version All

**Comment by candemiralp** [comment]
Hello @sarfarazbheda,

Thank you for raising this issue. We've created an implementation ticket to solve this issue.

Best Regards,
Can

**Comment by sarfarazbheda** [comment]
@candemiralp 

I have fixed this issue and raised PR also. If you can check and review it.

**Comment by Axel29** [comment]
Hi @RokPopov, @candemiralp , any update on this issue please?

**Comment by Axel29** [comment]
Hi again... Same question as two weeks ago, is there any update?

It's been months now and the bug is still present...

Thank you for your help.

**Comment by Axel29** [comment]
@candemiralp I created a pull request (https://github.com/Adyen/adyen-magento2/pull/2659) to fix the issue.

Everything seems to work with this code.

I don't know if this can be applied to this issue too, but I'll let you check.

**Comment by RokPopov** [comment]
Hi @Axel29, 

thank you for creating a PR, this is much appreciated. We have included the reviewing of the PR in the internal ticket. The issue has been prioritized accordingly internally, and we'll update this ticket once the solution has been reviewed.

Kind regards,
Rok

**Comment by sarfarazbheda** [comment]
Hello,

I already created PULL request and fixed this issue, if you can check and approve it.
https://github.com/Adyen/adyen-magento2/pull/2548

**Comment by Axel29** [comment]
> Hello,
> 
> I already created PULL request and fixed this issue, if you can check and approve it. #2548

Hi @sarfarazbheda , your PR didn't work for me with PayPal.
I'm not sure our bugs are the same, but @RokPopov closed my issue in order to merge it with yours.
My fix only concerns PayPal.

**Comment by candemiralp** [comment]
Hello @sarfarazbheda,

Thank you for raising this issue and appreciate your efforts for creating a pull request to solve this issue.

However, the fix #2548 can not be applied to `adyen-pm-method.js` file without any further logic as @khushboo-singhvi mentioned [here](https://github.com/Adyen/adyen-magento2/pull/2548/files#r1547916893). As the requested changes were not applied, the PR has not been merged.

The reason behind is that `onClick` event handler is not supported by all payment method components. The scope of this modifications should be limited in order not to affect the rest of the payment methods.

I hope this explains the reason behind the delay and not merging the PR. I would like to inform you that we will handle this bug soon.

Best Regards,
Can

**Comment by stutaylor** [comment]
Is there any updates for this - I have a client which needs this fixed too and it doesnt look like its moved for 10 months.

**Comment by f123248** [comment]
Hi @candemiralp @stutaylor @Axel29 @sarfarazbheda @RokPopov

The same PayPal issue still exists in V10.
However, I had already fixed this issue in V9, and the fix logic remains the same for both V9 and V10.
```javascript
                            onClick: function (resolve, reject) {
                                if (self.getTxVariant() === 'paypal') {
                                    return self.validate();
                                }

                                if (self.validate()) {
                                    resolve();
                                } else {
                                    reject();
                                }
                            },
```

Please review our fix patch, which is based on V10, and kindly confirm if you plan to merge it into the official release.

Best Regards,
Jack

[adyen-terms-adn-condition-validate-issue.patch](https://github.com/user-attachments/files/21916078/adyen-terms-adn-condition-validate-issue.patch)
