### ISSUE TITLE
Is version 2.3.0 compatible with Magento CE 2.2.5?

### ISSUE THREAD

**Issue by strajeru** [Adyen/adyen-magento2#288]
As the title suggests, this is more of a question than an issue.  
Feel free to answer yes/no and close the issue.  
**Magento version**: CE 2.2.5
**Plugin version**: 2.3.0
**Description**
I have this module installed on a Magento 2.2.5 version.  
I have Adyen HPP enabled. 
Everything looks ok until the payment step of the checkout.  
When selecting the Adyen HPP payment method, and hitting the  "Continue to Adyen" button, I get an error back saying "The payment method you requested is not available.".  
On a closer inspection, I noticed that in the request sent to `/V1/guest-carts/<cart hash here>/payment-information` the `paymentMethod` json element is an empty object `{}`.  
This does not happen for any other payment method I have. Core or custom.  
Not sure if this has something to do with the custom code I have or if this is a module problem.

**Comment by rikterbeek** [comment]
Hi @strajeru,

The extension works for 2.2.5. This issue seems familiar to me and is fixed in our latest release (2.3.0) https://github.com/Adyen/adyen-magento2/releases.

Regards,
Rik
Adyen

**Comment by strajeru** [comment]
@rikterbeek Thanks for the fast response. 
I will close this.

**Comment by strajeru** [comment]
@rikterbeek Just a small side note. 
I'm using version Adyen module version 2.3.0  and it still does not work for me. 
There is a high chance that I'm doing something wrong, but I want to leave this here maybe it's worth an analysis.  
In this line https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L249  
for me `self.method` always returns `undefined`.  
Changing `data.method = self.method` to `data.method = self.getCode()`, seems to solve the problem.
