### ISSUE TITLE
Wrong store id used for config settings, wrong api url is getting loaded. Related credit memo sync

### ISSUE THREAD

**Issue by govereem** [Adyen/adyen-magento2#494]
**Magento version**: 2.2.8
**Plugin version**: 4.2.1
**Description**

When creating a credit memo, Adyen is not receiving them from our Magento store.
We have 2 merchant accounts in our webshop, one is working fine. The other one fails. Payment methods are working fine, for both stores.

AdyenException: status 403, type:security Invalid Merchant Account code 901.

`AdyenLoggerTest.INFO: Request url to Adyen: shows te wrong url. The url showing is for our main store. Not the store where the order / credit memo was created. Zo this means the storeid is 1, the default and not using the config settings from the right store.

```
vendor/magento/module-sales/Model/Order/Payment.php Line: 675 the store id is correct.

But in vendor/adyen/module-payment/Gateway/Http/Client/TransactionRefund.php 
$this->_client = $this->_adyenHelper->initializeAdyenClient();

There is no storeId set. Method placeRequest will always use storeId 1
```

**Comment by cyattilakiss** [comment]
Hi @govereem ,

I created a branch where I uploaded a fix that I think should solve this issue. Can you please verify if this helps? 
https://github.com/Adyen/adyen-magento2/commit/70af7744889be38ee17c35695177abaed9908f3c

Thank you in advance,
Attila
Adyen

**Comment by govereem** [comment]
Hi Attila,

Thank you for trying to solve this problem.

Unfortunately this solution does not solve the problem, because
$storeManager->getStore()->getId(); wil return the default store, not the
store from the order.

With kind regards,
Gideon

Op do 8 aug. 2019 om 16:20 schreef cyattilakiss <notifications@github.com>:

**Comment by cyattilakiss** [comment]
Hi @govereem ,

I will dive a bit deeper then into this issue. I thought that we simply miss the storeId but indeed it needs to be retrieved with another approach.
If you can contribute and create a PR if you have a solution that would be appreciated :)

Best,
Attila

**Comment by govereem** [comment]
For now i fixed it by retrieving the order increment from reference, but
for workaround its fine, but not the best solution.

vendor/adyen/module-payment/Gateway/Http/Client/TransactionRefund.php


        \Magento\Sales\Model\OrderRepository $orderRepository,
        \Magento\Framework\Api\SearchCriteriaBuilder $searchCriteriaBuilder,

    public function
placeRequest(\Magento\Payment\Gateway\Http\TransferInterface
$transferObject)
    {
        $requests = $transferObject->getBody();

        if (isset($requests[0]['reference'])) {
            if ($order =
$this->getOrderByIncrementId($requests[0]['reference'])) {
                $this->_client =
$this->_adyenHelper->initializeAdyenClient($order->getStoreId());
            }
        }

        $responses = [];

        foreach ($requests as $request) {
            // call lib
            $service = new \Adyen\Service\Modification($this->_client);

            try {
                $responses[] = $service->refund($request);
            } catch (\Adyen\AdyenException $e) {
                $responses[] = null;
            }
        }
        return $responses;
    }

    public function getOrderByIncrementId($id)
    {
        $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter('increment_id', $id, 'eq')->create();
        $orderList =
$this->orderRepository->getList($searchCriteria)->getItems();

        if(count($orderList) < 1) {
            return false;
        }

        return end($orderList);
    }

Op ma 12 aug. 2019 om 11:24 schreef cyattilakiss <notifications@github.com>:

**Comment by ebaschiera** [comment]
I can confirm this issue. Not only refund is affected, but also cancellation and capture.
We patched the module like this: 
[adyen_multiple_merchant_account_300_3.patch.txt](https://github.com/Adyen/adyen-magento2/files/3514818/adyen_multiple_merchant_account_300_3.patch.txt)

**Comment by cyattilakiss** [comment]
Hi @govereem, @ebaschiera,

Thank you for the input. The fix has just been released in the version 6.0.0 but you can see the changes in the referenced pull request #653.

Let me know if you have any further questions or issues regarding this item.
I will close this issue for now but feel free to reopen it if you still experience it.

Best,
Attila
Adyen
