### ISSUE TITLE
[PW-3157] [iDeal] First notification is unsuccessful but a second notification 2 minutes later send a success response => order canceled but payment is in succes

### ISSUE THREAD

**Issue by chefbuitenhuis** [Adyen/adyen-magento2#717]
**Describe the bug**
Similar behavior as described in https://github.com/Adyen/adyen-magento2/issues/607. The first notification is unsuccesful but a second notification comes in which is succesful yet a order remains canceled.

**To Reproduce**
Steps to reproduce
1. Make sure iDeal links aren't automatically opened in your bank app
2. Create an order using iDeal
3. Once on bank page open the transaction in your app if prompted
4. Cancel the browser payment
5. Pay the bank app payment
6. This results in a canceled/closed order.

**Expected behavior**
I expect Adyen to reopen the order when a payment is made, even after the original one was canceled.

**Screenshots**

**Desktop (please complete the following information):**
Magento 2.3.4
Adyen 5.4.0

**Comment by cyattilakiss** [comment]
Hi @chefbuitenhuis ,

Thank you for raising this issue. This issue might be solved with this PR: #719 but to confirm that could you please attach a screenshot of your order notes - hiding of course the sensitive data from it - of an order when this happened?

Thank you in advance!
Best,
Attila
Adyen

**Comment by chefbuitenhuis** [comment]
Hi @cyattilakiss,

Thanks for your reply. It just happened again, see the screenshot for the offending order:
<img width="361" alt="Screenshot 2020-06-03 at 15 44 55" src="https://user-images.githubusercontent.com/7578636/83644209-5447af80-a5b1-11ea-9d3a-8a3c5f2962c4.png">

**Comment by cyattilakiss** [comment]
Hi @chefbuitenhuis ,

This issue has been fixed in the PR: #719
We are going to release this fix soon. I tag the PR with your issue number so you are going to get a notification when it's released.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @chefbuitenhuis ,

6.1.1 version has just been released. Let me know if you still face issues regarding this ticket.

Best,
Attila
Adyen

**Comment by Beagon** [comment]
Hi @cyattilakiss,

We still encounter this issue on version 6.4.0.


![image](https://user-images.githubusercontent.com/2945583/94793441-c2bf4180-03da-11eb-9f80-990b3ea56109.png)

**Comment by cyattilakiss** [comment]
Hi @Beagon ,

I reopened this issue and assigned a ticket number from our backlog: PW-3157
Could you please send your logs from the adyen folder related to this order to our support?
On your last screenshot I don't see the Cancellation only the authorisation, maybe it will be there in your longs.

Best,
Attila
Adyen

**Comment by Beagon** [comment]
@cyattilakiss,

I've sent the logs over to your support team. I could not spot anything weird about them except that they couldn't create an invoice

**Comment by cyattilakiss** [comment]
Thanks, got them.

**Comment by aneelfreelancer** [comment]
We are facing same issue, is they any update on this issue? Is it fixed in following version?
https://github.com/Adyen/adyen-magento2/releases/tag/6.6.1

**Comment by floorjubbega** [comment]
Hi @Beagon and @aneelfreelancer, 

Thank you for the feedback! This issue has now been resolved in release 6.6.8.
We suggest to update to our latest version, and let us know if you see any further issues.

Regards,
Floor
Adyen

**Comment by manaftryzens** [comment]
Hi there,

We are on 6.6.8 and we still have the same issue on our production environment. When the customer submits the 3d secure form he gets redirected to home page. Order remains in "Payment review" Status with the below comment in status history

Customer was redirected to bank for 3D-secure validation. Once the shopper authenticated, the order status will be updated accordingly.
Make sure that your notifications are being processed!
If the order is stuck on this status, the shopper abandoned the session. The payment can be seen as unsuccessful.
The order can be automatically cancelled based on the OFFER_CLOSED notification. Please contact Adyen Support to enable this.

This error is being thrown from vendor/adyen/module-payment/Controller/Process/Redirect.php, Line number : 244 onwards

**Comment by fahu** [comment]
@manaftryzens  Same here :(

@acampos1916 @cyattilakiss Can we please reopen this incident and take a look?
